### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mikesalvia**

### CODE REVIEW

**Comment by mikesalvia** [comment]
test this please

**Comment by wdsds** [comment]
ok to test

**Comment by mikesalvia** [comment]
retest this please

**Comment by mikesalvia** [comment]
ok to test

**Comment by mikesalvia** [comment]
retest this please

**Comment by DGHLJ** [comment]
retest this please

**Comment by DGHLJ** [comment]
retest this please

**Comment by mikesalvia** [comment]
retest this please

**Comment by mikesalvia** [comment]
ok to test

**Comment by mikesalvia** [comment]
Merging to master this should trigger a develop build within 15 minutes (polling interval)

**Comment by levonk** [comment]
Nice! @michaelsalvia

**Pull request merged**
